//
// Generated file, do not edit! Created by nedtool 5.5 from Messages/AlgoTimeout.msg.
//

#ifndef __ALGOTIMEOUT_M_H
#define __ALGOTIMEOUT_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



class AlgoTimeout;
/**
 * Class generated from <tt>Messages/AlgoTimeout.msg:17</tt> by nedtool.
 * <pre>
 * packet AlgoTimeout
 * {
 * }
 * </pre>
 */
class AlgoTimeout : public ::omnetpp::cPacket
{
  protected:

  private:
    void copy(const AlgoTimeout& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const AlgoTimeout&);

  public:
    AlgoTimeout(const char *name=nullptr, short kind=0);
    AlgoTimeout(const AlgoTimeout& other);
    virtual ~AlgoTimeout();
    AlgoTimeout& operator=(const AlgoTimeout& other);
    virtual AlgoTimeout *dup() const override {return new AlgoTimeout(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const AlgoTimeout& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, AlgoTimeout& obj) {obj.parsimUnpack(b);}

#endif // ifndef __ALGOTIMEOUT_M_H

