//
// Generated file, do not edit! Created by nedtool 5.5 from Messages/AppCoAck.msg.
//

#ifndef __INET_APPCOACK_M_H
#define __INET_APPCOACK_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif


namespace inet {

class AppCoAck;
} // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

#include "HostMessage_m.h" // import HostMessage


namespace inet {

/**
 * Class generated from <tt>Messages/AppCoAck.msg:25</tt> by nedtool.
 * <pre>
 * class AppCoAck extends HostMessage
 * {
 *     unsigned int id_h;
 *     unsigned int seq_S; /// seq du dernier message délivré
 *     unsigned int Ses;
 * }
 * </pre>
 */
class AppCoAck : public ::inet::HostMessage
{
  protected:
    unsigned int id_h = 0;
    unsigned int seq_S = 0;
    unsigned int Ses = 0;

  private:
    void copy(const AppCoAck& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const AppCoAck&);

  public:
    AppCoAck();
    AppCoAck(const AppCoAck& other);
    virtual ~AppCoAck();
    AppCoAck& operator=(const AppCoAck& other);
    virtual AppCoAck *dup() const override {return new AppCoAck(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual unsigned int getId_h() const;
    virtual void setId_h(unsigned int id_h);
    virtual unsigned int getSeq_S() const;
    virtual void setSeq_S(unsigned int seq_S);
    virtual unsigned int getSes() const;
    virtual void setSes(unsigned int Ses);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const AppCoAck& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, AppCoAck& obj) {obj.parsimUnpack(b);}

} // namespace inet

#endif // ifndef __INET_APPCOACK_M_H

