//
// Generated file, do not edit! Created by nedtool 5.5 from Messages/Apph_S.msg.
//

#ifndef __INET_APPH_S_M_H
#define __INET_APPH_S_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif


namespace inet {

class Apph_S;
} // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

#include "HostMessage_m.h" // import HostMessage

// cplusplus {{
  
    #include "../commun_f.h"
// }}


namespace inet {

// cplusplus {{
    typedef idMsg idMsgApph_S;
// }}

/**
 * Class generated from <tt>Messages/Apph_S.msg:38</tt> by nedtool.
 * <pre>
 * class Apph_S extends HostMessage
 * {
 *     idMsgApph_S id;
 *     unsigned int Ses;
 * }
 * </pre>
 */
class Apph_S : public ::inet::HostMessage
{
  protected:
    idMsgApph_S id;
    unsigned int Ses = 0;

  private:
    void copy(const Apph_S& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Apph_S&);

  public:
    Apph_S();
    Apph_S(const Apph_S& other);
    virtual ~Apph_S();
    Apph_S& operator=(const Apph_S& other);
    virtual Apph_S *dup() const override {return new Apph_S(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const idMsgApph_S& getId() const;
    virtual idMsgApph_S& getIdForUpdate() { handleChange();return const_cast<idMsgApph_S&>(const_cast<Apph_S*>(this)->getId());}
    virtual void setId(const idMsgApph_S& id);
    virtual unsigned int getSes() const;
    virtual void setSes(unsigned int Ses);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Apph_S& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Apph_S& obj) {obj.parsimUnpack(b);}

} // namespace inet

#endif // ifndef __INET_APPH_S_M_H

