//
// Generated file, do not edit! Created by nedtool 5.5 from Messages/HostMessage.msg.
//

#ifndef __INET_HOSTMESSAGE_M_H
#define __INET_HOSTMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif


namespace inet {

class HostMessage;
} // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk


namespace inet {

/**
 * Class generated from <tt>Messages/HostMessage.msg:23</tt> by nedtool.
 * <pre>
 * class HostMessage extends FieldsChunk
 * {
 *     unsigned int cellId;
 * }
 * </pre>
 */
class HostMessage : public ::inet::FieldsChunk
{
  protected:
    unsigned int cellId = 0;

  private:
    void copy(const HostMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const HostMessage&);

  public:
    HostMessage();
    HostMessage(const HostMessage& other);
    virtual ~HostMessage();
    HostMessage& operator=(const HostMessage& other);
    virtual HostMessage *dup() const override {return new HostMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual unsigned int getCellId() const;
    virtual void setCellId(unsigned int cellId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const HostMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, HostMessage& obj) {obj.parsimUnpack(b);}

} // namespace inet

#endif // ifndef __INET_HOSTMESSAGE_M_H

