//
// Generated file, do not edit! Created by nedtool 5.5 from Messages/Req1.msg.
//

#ifndef __INET_REQ1_M_H
#define __INET_REQ1_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif


namespace inet {

class Req1;
} // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

#include "FIFOCom_m.h" // import FIFOCom

// cplusplus {{
  
    #include "../commun_f.h"
    #include "../MobileSupportStations/StationGroup.h"
// }}


namespace inet {

// cplusplus {{
    
    #include <vector> 
    typedef StationGroup StationGroupReq1;
// }}

/**
 * Class generated from <tt>Messages/Req1.msg:39</tt> by nedtool.
 * <pre>
 * class Req1 extends FIFOCom
 * {
 *     unsigned int id_h;
 *     unsigned int seq_S;
 *     unsigned int Ses_LC;
 *     unsigned int Ses;
 *     StationGroupReq1 MSSb;
 * }
 * </pre>
 */
class Req1 : public ::inet::FIFOCom
{
  protected:
    unsigned int id_h = 0;
    unsigned int seq_S = 0;
    unsigned int Ses_LC = 0;
    unsigned int Ses = 0;
    StationGroupReq1 MSSb;

  private:
    void copy(const Req1& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Req1&);

  public:
    Req1();
    Req1(const Req1& other);
    virtual ~Req1();
    Req1& operator=(const Req1& other);
    virtual Req1 *dup() const override {return new Req1(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual unsigned int getId_h() const;
    virtual void setId_h(unsigned int id_h);
    virtual unsigned int getSeq_S() const;
    virtual void setSeq_S(unsigned int seq_S);
    virtual unsigned int getSes_LC() const;
    virtual void setSes_LC(unsigned int Ses_LC);
    virtual unsigned int getSes() const;
    virtual void setSes(unsigned int Ses);
    virtual const StationGroupReq1& getMSSb() const;
    virtual StationGroupReq1& getMSSbForUpdate() { handleChange();return const_cast<StationGroupReq1&>(const_cast<Req1*>(this)->getMSSb());}
    virtual void setMSSb(const StationGroupReq1& MSSb);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Req1& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Req1& obj) {obj.parsimUnpack(b);}

} // namespace inet

#endif // ifndef __INET_REQ1_M_H

