//
// Generated file, do not edit! Created by nedtool 5.5 from Messages/Req2.msg.
//

#ifndef __INET_REQ2_M_H
#define __INET_REQ2_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif


namespace inet {

class Req2;
} // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

#include "FIFOCom_m.h" // import FIFOCom

// cplusplus {{
  
    #include "../commun_f.h"
    #include "../MobileSupportStations/StationGroup.h"
// }}


namespace inet {

// cplusplus {{
    
    #include <vector> 
    typedef StationGroup StationGroupReq2;
    typedef std::vector<idMsg> idMsgVectorReq2;
// }}

/**
 * Class generated from <tt>Messages/Req2.msg:43</tt> by nedtool.
 * <pre>
 * class Req2 extends FIFOCom
 * {
 *     unsigned int id_h;
 *     idMsgVectorReq2 msg_req;
 *     unsigned int Ses;
 *     StationGroupReq2 MSSb;
 * }
 * </pre>
 */
class Req2 : public ::inet::FIFOCom
{
  protected:
    unsigned int id_h = 0;
    idMsgVectorReq2 msg_req;
    unsigned int Ses = 0;
    StationGroupReq2 MSSb;

  private:
    void copy(const Req2& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Req2&);

  public:
    Req2();
    Req2(const Req2& other);
    virtual ~Req2();
    Req2& operator=(const Req2& other);
    virtual Req2 *dup() const override {return new Req2(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual unsigned int getId_h() const;
    virtual void setId_h(unsigned int id_h);
    virtual const idMsgVectorReq2& getMsg_req() const;
    virtual idMsgVectorReq2& getMsg_reqForUpdate() { handleChange();return const_cast<idMsgVectorReq2&>(const_cast<Req2*>(this)->getMsg_req());}
    virtual void setMsg_req(const idMsgVectorReq2& msg_req);
    virtual unsigned int getSes() const;
    virtual void setSes(unsigned int Ses);
    virtual const StationGroupReq2& getMSSb() const;
    virtual StationGroupReq2& getMSSbForUpdate() { handleChange();return const_cast<StationGroupReq2&>(const_cast<Req2*>(this)->getMSSb());}
    virtual void setMSSb(const StationGroupReq2& MSSb);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Req2& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Req2& obj) {obj.parsimUnpack(b);}

} // namespace inet

#endif // ifndef __INET_REQ2_M_H

