//
// Generated file, do not edit! Created by nedtool 5.5 from Messages/Rsp2.msg.
//

#ifndef __INET_RSP2_M_H
#define __INET_RSP2_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif


namespace inet {

class Rsp2;
} // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

#include "FIFOCom_m.h" // import FIFOCom

// cplusplus {{
  
    #include "../commun_f.h"
// }}


namespace inet {

// cplusplus {{
    
    #include <vector> 
    typedef std::vector<idMsg> idMsgVectorRsp2;
// }}

/**
 * Class generated from <tt>Messages/Rsp2.msg:37</tt> by nedtool.
 * <pre>
 * class Rsp2 extends FIFOCom
 * {
 *     unsigned int id_h;
 *     idMsgVectorRsp2 msg;
 *     idMsgVectorRsp2 msg_rcv;
 *     unsigned int Ses;
 * }
 * </pre>
 */
class Rsp2 : public ::inet::FIFOCom
{
  protected:
    unsigned int id_h = 0;
    idMsgVectorRsp2 msg;
    idMsgVectorRsp2 msg_rcv;
    unsigned int Ses = 0;

  private:
    void copy(const Rsp2& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Rsp2&);

  public:
    Rsp2();
    Rsp2(const Rsp2& other);
    virtual ~Rsp2();
    Rsp2& operator=(const Rsp2& other);
    virtual Rsp2 *dup() const override {return new Rsp2(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual unsigned int getId_h() const;
    virtual void setId_h(unsigned int id_h);
    virtual const idMsgVectorRsp2& getMsg() const;
    virtual idMsgVectorRsp2& getMsgForUpdate() { handleChange();return const_cast<idMsgVectorRsp2&>(const_cast<Rsp2*>(this)->getMsg());}
    virtual void setMsg(const idMsgVectorRsp2& msg);
    virtual const idMsgVectorRsp2& getMsg_rcv() const;
    virtual idMsgVectorRsp2& getMsg_rcvForUpdate() { handleChange();return const_cast<idMsgVectorRsp2&>(const_cast<Rsp2*>(this)->getMsg_rcv());}
    virtual void setMsg_rcv(const idMsgVectorRsp2& msg_rcv);
    virtual unsigned int getSes() const;
    virtual void setSes(unsigned int Ses);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Rsp2& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Rsp2& obj) {obj.parsimUnpack(b);}

} // namespace inet

#endif // ifndef __INET_RSP2_M_H

