//
// Generated file, do not edit! Created by nedtool 5.5 from Messages/timeout.msg.
//

#ifndef __TIMEOUT_M_H
#define __TIMEOUT_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



class Timeout2;
/**
 * Class generated from <tt>Messages/timeout.msg:19</tt> by nedtool.
 * <pre>
 * // type 0 BROADCAST
 * // type 1 BROADCAST_CO
 * // type 2 RESP_INIT
 * packet Timeout2
 * {
 *     unsigned int seq;
 *     unsigned int type;
 *     unsigned int newMH;
 *     unsigned int Ses;
 * }
 * </pre>
 */
class Timeout2 : public ::omnetpp::cPacket
{
  protected:
    unsigned int seq = 0;
    unsigned int type = 0;
    unsigned int newMH = 0;
    unsigned int Ses = 0;

  private:
    void copy(const Timeout2& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Timeout2&);

  public:
    Timeout2(const char *name=nullptr, short kind=0);
    Timeout2(const Timeout2& other);
    virtual ~Timeout2();
    Timeout2& operator=(const Timeout2& other);
    virtual Timeout2 *dup() const override {return new Timeout2(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual unsigned int getSeq() const;
    virtual void setSeq(unsigned int seq);
    virtual unsigned int getType() const;
    virtual void setType(unsigned int type);
    virtual unsigned int getNewMH() const;
    virtual void setNewMH(unsigned int newMH);
    virtual unsigned int getSes() const;
    virtual void setSes(unsigned int Ses);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Timeout2& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Timeout2& obj) {obj.parsimUnpack(b);}

#endif // ifndef __TIMEOUT_M_H

